# _config.yml

title: John Wesley Paige Jr. | Portfolio
email: John.Paige@johnwesleypaigejr.com
description: >-
  The professional portfolio and blog for John Wesley Paige Jr., a cybersecurity 
  and cloud professional.
baseurl: "" # for root domain, keep empty
url: "https://johnwesleypaigejr.com"
github_username: ICaintSpell
linkedin_username: john-paige-jr-09149997

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude these files/folders from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Optional: set markdown parser and syntax highlighter
markdown: kramdown
kramdown:
  input: GFM

highlighter: rouge
