backend:
  name: git-gateway
  branch: main  # change if your default branch is different

media_folder: "public/uploads"  # where uploaded media files will be stored
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "_posts"      # Your posts folder here
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
